[[projects]]
name = "Climb Tracker"
url = "https://github.com/DingoEatingFuzz/chrome-emoji-skin-tone-randomizer"
year = 2016
tags = [ "JavaScript", "React", "Firebase" ]
thumbnail = "/images/climb-tracker.png"
description = """
A simple web app for tracking bouldering workouts. It focuses on quickly marking which problems were completed and which were attempted. In this way, at the end of the workout, a histogram and tally of problems and problem difficulties is plotted. There are also monthly reports to look back on.
"""

[[projects]]
name = "Emoji Skin Tone Randomizer"
url = "https://github.com/DingoEatingFuzz/chrome-emoji-skin-tone-randomizer"
year = 2016
tags = [ "JavaScript", "Chrome" ]
thumbnail = "/images/emoji-skin-tones.png"
description = """
A chrome extension for assigning a random skin tone to a skin tone eligible emoji that doesn't already have one assigned.
"""

[[projects]]
name = "Headers Middleman"
url = "https://github.com/DingoEatingFuzz/chrome-headers-middleman"
year = 2015
tags = [ "JavaScript", "React", "Chrome" ]
thumbnail = "/images/headers-middle-man.png"
description = """
A chrome extension for modifying the headers of HTTP Requests based on regex pattern matching.
"""

[[projects]]
name = "NPR Music We Love Bookmarklets"
url = "https://github.com/DingoEatingFuzz/npr-music-we-love-bookmarklets"
year = 2015
tags = [ "JavaScript", "Browsers" ]
thumbnail = "/images/npr-songs-we-love.png"
description = """
The NPR Music We Love app was a wonderful things, but it had no way to pin/favorite/star/save the tracks you liked. This was solvable in many ways, but the way that sounded the most interesting at the time was bookmarklets. With a click of a bookmarklet, the track would be saved to localstorage. I went overboard and created additional bookmarklets for seeing the track list and for disliking tracks. You know, just for fun.
"""

[[projects]]
name = "Github Avatar Arrangement"
url = "https://github.com/DingoEatingFuzz/github-gravatars"
year = 2014
tags = [ "Python", "Processing" ]
thumbnail = "/images/github-gravatars.png"
description = """
A quick sketch that generates all possible Github Avatars (not including color variations). Since Github default avatars are created through the toggling of 15 states, the resulting space is only 2<sup>15</sup>. Which is high, but not so high it isn't presentable in a single image.
"""
